services:
  - type: web
    name: chatbot-platform
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app.database import create_tables; create_tables()"
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        value: "your-openai-key-here"  # You'll set this in Render dashboard

databases:
  - name: chatbot-db
    plan: free
    databaseName: chatbot
    user: chatbot_user
